2019-07-28 23:12:01,494 ERROR: Exception on /searchn [GET] [in D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PythonProjects\Flask\Nature'sDoctors\silvapermaculture\plants\routes.py", line 130, in searchn
    return redirect(url_for('plants.plants'))
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'plants.plants'. Did you mean 'plants.plant' instead?
2019-07-28 23:13:03,058 INFO: Silvapermaculture startup [in D:\PythonProjects\Flask\Nature'sDoctors\silvapermaculture\__init__.py:55]
2019-07-28 23:13:56,705 INFO: Silvapermaculture startup [in D:\PythonProjects\Flask\Nature'sDoctors\silvapermaculture\__init__.py:55]
2019-07-28 23:13:56,705 INFO: Silvapermaculture startup [in D:\PythonProjects\Flask\Nature'sDoctors\silvapermaculture\__init__.py:55]
2019-07-28 23:14:14,755 INFO: Silvapermaculture startup [in D:\PythonProjects\Flask\Nature'sDoctors\silvapermaculture\__init__.py:55]
2019-07-28 23:14:27,942 ERROR: Exception on /searchn [GET] [in D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PythonProjects\Flask\Nature'sDoctors\silvapermaculture\plants\routes.py", line 130, in searchn
    return redirect(url_for('plants.plants'))
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "D:\PythonProjects\Flask\Environments\Nature'sDoctors\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'plants.plants'. Did you mean 'plants.plant' instead?
2019-07-28 23:16:48,769 INFO: Silvapermaculture startup [in D:\PythonProjects\Flask\Nature'sDoctors\silvapermaculture\__init__.py:55]
